add_newline = true
format = "$battery$directory[»](bold #64AECC) "

[python]
symbol = " "

[battery]
full_symbol        = "•"
charging_symbol    = "⇡"
discharging_symbol = "⇣"
format             = "[$symbol$percentage]($style) "

[[battery.display]]
threshold = 40
style     = "bold yellow"

[directory]
style = "bold white"
truncation_length=1

[time]
disabled = true
